name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy
    - name: Build
      run: rustup run nightly cargo build --verbose
    - name: Run tests
      run: rustup run nightly cargo test --verbose
    - name: Run lints
      run: rustup run nightly cargo clippy --verbose